#!/bin/csh
# 	$Id: run-tests,v 1.2 2005/06/22 00:44:46 rocky Exp $	
set program="../lead_sentence.pl"
foreach file ( {brief*,bug*,test*} )
    echo "${file}:"
    $program -rating --ellipsis --nl --file $file
    echo "------------"
end
